theme: jekyll-theme-minimal
title: "Mack Gray"
description: <strong>Mack Gray</strong>, Web Developer
location: Toronto, Canada
email: mack@mackgray.me
show_downloads: false
google_analytics: UA-33131705-3