theme: jekyll-theme-minimal
title: "Mack Gray"
description: Home page of Mack Gray, Web Developer
location: Toronto, Canada
email: mack@mackgray.me
show_downloads: false
google_analytics: UA-33131705-3